name: Metrics (WakaTime)

on:
  # Schedule updates
  schedule: [{ cron: "0 0 * * 4" }]
  # The line below let you run workflow manually
  workflow_dispatch:

jobs:
  # ⏰ WakaTime plugin
  plugin-wakatime:
    name: WakaTime
    runs-on: ubuntu-latest
    steps:
      - name: plugin wakatime
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 1
          repositories_batch: 1
          repositories_forks: no
          repositories_affiliations: owner, collaborator, organization_member
          filename: assets/metrics.plugin.wakatime.svg
          use_prebuilt_image: yes
          output_action: pull-request
          committer_message: "chore(metrics): update `${filename}`"
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }} # Required
          plugin_wakatime_days: 30 # Display last week stats
          plugin_wakatime_sections: time, languages, editors, languages-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 5 # Show 5 entries per graph
          plugin_wakatime_url: https://wakatime.com # Wakatime url endpoint
          plugin_wakatime_user: .user.login # User
          plugin_wakatime_languages_other: yes
          plugin_wakatime_languages_ignored: markdown, json, yaml, text, xml, sh, properties, tsconfig, mdx, locale, shell script, gitignore file, gettext catalog, solidity file # Ignored languages
