name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: nekofar
          template: classic
          base: activity, community, repositories, metadata
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_display: large
          config_timezone: Asia/Tehran
          use_prebuilt_image: no
          committer_message: 'chore(metrics): update ${filename} - [Skip GitHub Action]'
          
          plugin_languages: yes
          plugin_languages_ignored: actionscript, makefile, c, batchfile
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_languages_indepth: true
          plugin_languages_details: lines, percentage
          
          plugin_wakatime: no
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com/@nekofar
          plugin_wakatime_user: current
          
          plugin_achievements: yes
          plugin_achievements_threshold: B
          
