name: Metrics (Followup)

on:
  # Schedule updates
  schedule: [{ cron: "0 4 * * *" }]
  # The line below let you run workflow manually
  workflow_dispatch:

jobs:
  # 🎟️  Follow-up of issues and pull requests
  plugin-followup:
    name: Followup issues
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: plugin followup
        uses: nekofar/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 500
          repositories_batch: 100
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Asia/Tehran
          filename: assets/metrics.plugin.followup.svg
          use_prebuilt_image: yes
          output_action: pull-request
          committer_message: "chore(metrics): update `${filename}`"
          plugin_followup: yes
          plugin_followup_sections: repositories, user # Display overall status of issues/pull requests created on user's repositories and created by user
          plugin_followup_indepth: yes
          plugin_followup_archived: yes
