name: Metrics (Repositories)

on:
  # Schedule updates
  schedule: [{ cron: "0 7 * * *" }]
  # The line below let you run workflow manually
  workflow_dispatch:

jobs:
  # 🗃️  Base content: Repositories
  repositories:
    name: Repositories
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: repositories
        uses: nekofar/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          repositories: 500
          repositories_batch: 100
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Asia/Tehran
          filename: assets/metrics.base.repositories.svg
          use_prebuilt_image: yes
          output_action: pull-request
          committer_message: "chore(metrics): update `${filename}`"
