name: Metrics (Languages)

on:
  # Schedule updates
  schedule: [{ cron: "0 0 * * 4" }]
  # The line below let you run workflow manually
  workflow_dispatch:

jobs:
  # 🈷️ Most used languages
  plugin-languages:
    name: Most used languages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: plugin languages
        uses: nekofar/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          base_indepth: true
          repositories: 500
          repositories_batch: 100
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          filename: assets/metrics.plugin.languages.svg
          use_prebuilt_image: yes
          output_action: pull-request
          committer_message: "chore(metrics): update `${filename}`"
          plugin_languages: yes
          plugin_languages_ignored: ActionScript, AngelScript # Ignored languages
          plugin_languages_skipped: "nekofar/nekofar" # List of repositories to skip
          plugin_languages_limit: 8 # Display up to 8 languages
          plugin_languages_threshold: 0% # Hides all languages less than 2%
          plugin_languages_colors: github # Make most used languages orange and JavaScript red
          plugin_languages_aliases: RenderScript:Rust, TSX:TypeScript, JSX:JavaScript # Customize languages names with aliases
          plugin_languages_sections: most-used, recently-used # Display most used and recently used languages stats
          plugin_languages_details: percentage # Additionally display total bytes size and percentage
          plugin_languages_indepth: yes # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 60 # Indepth mode - Analysis timeout
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: programming # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 1000 # Load up to 1000 events to compute recently used stats
          plugin_languages_recent_days: 30 # Events maximum age (day, recently-used section)
          commits_authoring: ${{ secrets.AUTHOR_EMAILS }} # Surnames or email addresses used to identify your commits
