name: Metrics (Activity)

on:
  # Schedule updates
  schedule: [{ cron: "0 2 * * *" }]
  # The line below let you run workflow manually
  workflow_dispatch:

jobs:
  # 🗃️  Base content: Activity & Community
  activity-community:
    name: Activity & Community
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: activity & community
        uses: nekofar/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community
          base_indepth: yes
          repositories: 500
          repositories_batch: 100
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Asia/Tehran
          filename: assets/metrics.base.activity-community.svg
          use_prebuilt_image: yes
          output_action: pull-request
          committer_message: "chore(metrics): update `${filename}`"
